In [1]:
import numpy as np
import pandas as pd
import math as m
import matplotlib.pyplot as plt
import glob
import datetime as dt

In [7]:
data = pd.read_csv('/Users/alessandrocantarelli/Documents/Tec/PD sensor extracted data/2021-03-15.csv', index_col=[0])
data.head()

/Users/alessandrocantarelli/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

,id,tso,ts,mc,bt,acc_1_t,acc_1_x,acc_1_y,acc_1_z,acc_2_t,...,acc_4_y,acc_4_z,acc_5_t,acc_5_x,acc_5_y,acc_5_z,acc_6_t,acc_6_x,acc_6_y,acc_6_z
0,a0:e6:f8:01:00:c0,1.614344e+09,142230015.0,43053,2021-03-14 23:59:51.030,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.064,0.04,-1.056,0.256,-0.064,0,-1.024,0.256,-0.096
1,a0:e6:f8:01:00:c1,NaN,NaN,58514,2021-03-14 23:59:57.344,0.18,-0.064,-0.064,-1.024,0.14,...,-0.064,-1.024,0.04,-0.064,-0.064,-1.024,0,-0.064,-0.064,-1.024
2,a0:e6:f8:01:00:c2,1.614344e+09,142229929.0,13802,2021-03-14 23:59:50.169,0.18,-0.736,-0.064,-0.736,0.14,...,-0.064,-0.736,0.04,-0.704,-0.064,-0.736,0,-0.704,-0.064,-0.736
3,a0:e6:f8:01:00:c1,1.614344e+09,142229747.0,58471,2021-03-14 23:59:48.347,0.18,-0.064,-0.064,-1.024,0.14,...,-0.064,-1.024,0.04,-0.064,-0.064,-1.024,0,-0.064,-0.064,-1.024
4,a0:e6:f8:01:00:c0,1.614344e+09,142229696.0,43038,2021-03-14 23:59:47.837,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.096,0.04,-1.056,0.256,-0.096,0,-1.056,0.256,-0.064

In [9]:
def separate_participants(data, label):
    grouped = data.groupby(data.id)
    df1 = grouped.get_group(label)
    df1 = df1.sort_values(by=['bt'])
    df1 = df1.reset_index(drop=True)
    return df1

In [10]:
PDL = separate_participants(data, 'a0:e6:f8:01:00:c0') 
PDL
#PDR = separate_participants(data, 'a0:e6:f8:01:00:c1')
#CNL = separate_participants(data, 'a0:e6:f8:01:00:c3')
#CNR = separate_participants(data, 'a0:e6:f8:01:00:c2')

,id,tso,ts,mc,bt,acc_1_t,acc_1_x,acc_1_y,acc_1_z,acc_2_t,...,acc_4_y,acc_4_z,acc_5_t,acc_5_x,acc_5_y,acc_5_z,acc_6_t,acc_6_x,acc_6_y,acc_6_z
0,a0:e6:f8:01:00:c0,1.614344e+09,142229675.0,43037,2021-03-14 23:59:47.627,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.064,0.04,-1.056,0.256,-0.096,0,-1.056,0.256,-0.096
1,a0:e6:f8:01:00:c0,1.614344e+09,142229696.0,43038,2021-03-14 23:59:47.837,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.096,0.04,-1.056,0.256,-0.096,0,-1.056,0.256,-0.064
2,a0:e6:f8:01:00:c0,1.614344e+09,142229718.0,43039,2021-03-14 23:59:48.057,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.096,0.04,-1.056,0.256,-0.064,0,-1.056,0.256,-0.064
3,a0:e6:f8:01:00:c0,1.614344e+09,142229741.0,43040,2021-03-14 23:59:48.287,0.18,-1.056,0.256,-0.064,0.14,...,0.256,-0.064,0.04,-1.056,0.256,-0.064,0,-1.056,0.256,-0.064
4,a0:e6:f8:01:00:c0,1.614344e+09,142229762.0,43041,2021-03-14 23:59:48.497,0.18,-1.056,0.256,-0.096,0.14,...,0.256,-0.064,0.04,-1.056,0.256,-0.096,0,-1.056,0.256,-0.064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378699,a0:e6:f8:01:00:c0,1.614344e+09,150861036.0,41750,2021-03-15 23:59:40.143,0.18,0.256,0.960,0.000,0.14,...,0.960,0.000,0.04,0.256,0.992,0.032,0,0.256,0.960,0.000
378700,a0:e6:f8:01:00:c0,1.614344e+09,150861059.0,41751,2021-03-15 23:59:40.373,0.18,0.256,0.992,0.000,0.14,...,0.992,0.032,0.04,0.256,0.960,0.032,0,0.256,0.992,0.064
378701,a0:e6:f8:01:00:c0,1.614344e+09,150861077.0,41752,2021-03-15 23:59:40.533,0.18,0.256,0.928,0.032,0.14,...,0.960,0.064,0.04,0.288,0.960,0.032,0,0.288,0.960,0.032
378702,a0:e6:f8:01:00:c0,1.614344e+09,150861099.0,41753,2021-03-15 23:59:40.753,0.18,0.256,0.928,0.032,0.14,...,0.992,0.064,0.04,0.288,0.960,0.032,0,0.288,0.960,0.064
378703,a0:e6:f8:01:00:c0,1.614344e+09,150861102.0,41754,2021-03-15 23:59:40.783,0.18,0.256,0.928,0.064,0.14,...,0.960,0.032,0.04,0.288,0.960,0.064,0,0.288,0.928,0.064

In [27]:
def separate_data(data):
    timestamp = []
    x = []
    y = []
    z = []
    for i in range(len(data)):
        test = data.iloc[i]
        # getting correct timestamp
        date = pd.to_datetime(test[4])
        t1 = dt.timedelta(seconds=test[21])
        t2 = dt.timedelta(seconds=test[17])
        t3 = dt.timedelta(seconds=test[13])
        t4 = dt.timedelta(seconds=test[9])
        t5 = dt.timedelta(seconds=test[5])
        timestamp.append(date)
        timestamp.append(date + t1)
        timestamp.append(date + t2)
        timestamp.append(date + t3)
        timestamp.append(date + t4)
        timestamp.append(date + t5)
        # extract x,y,z
        x.append(test[26])
        y.append(test[27])
        z.append(test[28])
        x.append(test[22])
        y.append(test[23])
        z.append(test[24])
        x.append(test[18])
        y.append(test[19])
        z.append(test[20])
        x.append(test[14])
        y.append(test[15])
        z.append(test[16])
        x.append(test[10])
        y.append(test[11])
        z.append(test[12])
        x.append(test[6])
        y.append(test[7])
        z.append(test[8])
    dataframe = pd.DataFrame({"t": timestamp, "x": x, "y": y, "z": z})
    return dataframe

In [28]:
PDLfinal = separate_data(PDL) 
PDRfinal = separate_data(PDR)
CNLfinal = separate_data(CNL)
CNRfinal = separate_data(CNR)

In [29]:
PDLfinal.to_csv('C:/Users/ale/Documents/Tec/PD sensor extracted data/PDdata/2021-03-18/PD_left.csv', index = False)
PDRfinal.to_csv('C:/Users/ale/Documents/Tec/PD sensor extracted data/PDdata/2021-03-18/PD_right.csv', index = False)
CNLfinal.to_csv('C:/Users/ale/Documents/Tec/PD sensor extracted data/PDdata/2021-03-18/CN_left.csv', index = False)
CNRfinal.to_csv('C:/Users/ale/Documents/Tec/PD sensor extracted data/PDdata/2021-03-18/CN_right.csv', index = False)