In [1]:
import numpy as np
import pandas as pd
import math as m
import matplotlib.pyplot as plt
import glob

In [17]:
data = pd.read_excel('C:/Users/ale/Documents/Tec/PD sensor extracted data/supportive documents/Turning_new.xls')
data.head(2254)

,Time (in UTC),Date,Timestamp start of Turning,Participant ID number,PD_or_C,type_of_turn,number_of_turning_steps,turning_angle,Turning duration,On or Off medication/DBS state,Clinical_assessment,Scripted_activity,Relative time from the video start,File name
0,14:35:28.756999,2020-11-02,1604327728,1029,C,pivot_turn,4,90_degrees,1.980999,Control,No,Yes,00:00:13.500,1028-1029_02.11.20_annotations_set4_from 16043...
1,14:35:32.537999,2020-11-02,1604327732,1029,C,pivot_turn,2,90_degrees,1.028000,Control,No,Yes,00:00:17.281,1028-1029_02.11.20_annotations_set4_from 16043...
2,14:35:49.809999,2020-11-02,1604327749,1029,C,pivot_turn,2,90_degrees,1.278000,Control,No,Yes,00:00:34.553,1028-1029_02.11.20_annotations_set4_from 16043...
3,14:35:55.124999,2020-11-02,1604327755,1029,C,pivot_turn,2,90_degrees,1.020000,Control,No,Yes,00:00:39.868,1028-1029_02.11.20_annotations_set4_from 16043...
4,14:36:41.460000,2020-11-02,1604327801,1029,C,pivot_turn,2,90_degrees,1.092999,Control,No,Yes,00:01:26.203,1028-1029_02.11.20_annotations_set4_from 16043...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249,12:03:17.897000,2021-03-04,1614859397,1030,PD,pivot_turn,2,90_degrees,1.428999,On medication - On DBS,No,Yes,00:02:30.168,1030-1031_04.03.21_annotations_set10_from 1614...
2250,12:03:55.683000,2021-03-04,1614859435,1030,PD,pivot_turn,2,90_degrees,1.095000,On medication - On DBS,No,Yes,00:03:07.954,1030-1031_04.03.21_annotations_set10_from 1614...
2251,12:04:26.694999,2021-03-04,1614859466,1030,PD,pivot_turn,1,90_degrees,1.516000,On medication - On DBS,No,No,00:00:50.983,1030-1031_04.03.21_annotations_set13_from 1614...
2252,15:10:42.983000,2021-03-15,1615821042,1011,C,pivot_turn,2,135_degrees,2.047999,Control,No,No,00:00:57.351,1010-1011_15.03.21_annotations_set1_from 16158...
2253,15:11:10.151000,2021-03-15,1615821070,1011,C,pivot_turn,2,90_degrees,1.808999,Control,No,Yes,00:01:24.519,1010-1011_15.03.21_annotations_set1_from 16158...

In [19]:
data['t'] = data['Date'] + ' ' + data['Time (in UTC)']
data['t'] = pd.to_datetime(data['t'])
data.head()

,Time (in UTC),Date,Timestamp start of Turning,Participant ID number,PD_or_C,type_of_turn,number_of_turning_steps,turning_angle,Turning duration,On or Off medication/DBS state,Clinical_assessment,Scripted_activity,Relative time from the video start,File name,t
0,14:35:28.756999,2020-11-02,1604327728,1029,C,pivot_turn,4,90_degrees,1.980999,Control,No,Yes,00:00:13.500,1028-1029_02.11.20_annotations_set4_from 16043...,2020-11-02 14:35:28.756999
1,14:35:32.537999,2020-11-02,1604327732,1029,C,pivot_turn,2,90_degrees,1.028000,Control,No,Yes,00:00:17.281,1028-1029_02.11.20_annotations_set4_from 16043...,2020-11-02 14:35:32.537999
2,14:35:49.809999,2020-11-02,1604327749,1029,C,pivot_turn,2,90_degrees,1.278000,Control,No,Yes,00:00:34.553,1028-1029_02.11.20_annotations_set4_from 16043...,2020-11-02 14:35:49.809999
3,14:35:55.124999,2020-11-02,1604327755,1029,C,pivot_turn,2,90_degrees,1.020000,Control,No,Yes,00:00:39.868,1028-1029_02.11.20_annotations_set4_from 16043...,2020-11-02 14:35:55.124999
4,14:36:41.460000,2020-11-02,1604327801,1029,C,pivot_turn,2,90_degrees,1.092999,Control,No,Yes,00:01:26.203,1028-1029_02.11.20_annotations_set4_from 16043...,2020-11-02 14:36:41.460000

In [21]:
startdate = pd.to_datetime('2021-03-16 22:30:00.000')
enddate = pd.to_datetime('2021-03-17 09:00:00.000')

mask = (data['t'] > startdate) & (data['t'] <= enddate)
sleep_1 = data.loc[mask]
sleep_1

,Time (in UTC),Date,Timestamp start of Turning,Participant ID number,PD_or_C,type_of_turn,number_of_turning_steps,turning_angle,Turning duration,On or Off medication/DBS state,Clinical_assessment,Scripted_activity,Relative time from the video start,File name,t
2430,08:28:51.868000,2021-03-17,1615969731,1010,PD,pivot_turn,2,135_degrees,2.191000,On medication - On DBS,No,No,00:01:16.332,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:28:51.868000
2431,08:28:56.368000,2021-03-17,1615969736,1010,PD,pivot_turn,3,135_degrees,2.191000,On medication - On DBS,No,No,00:01:20.832,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:28:56.368000
2432,08:29:06.249000,2021-03-17,1615969746,1010,PD,pivot_turn,1,90_degrees,1.809999,On medication - On DBS,No,No,00:01:30.713,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:29:06.249000
2433,08:29:13.559000,2021-03-17,1615969753,1010,PD,pivot_turn,1,90_degrees,1.191000,On medication - On DBS,No,No,00:01:38.023,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:29:13.559000
2434,08:29:20.321000,2021-03-17,1615969760,1010,PD,pivot_turn,2,90_degrees,1.809999,On medication - On DBS,No,No,00:01:44.785,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:29:20.321000
2435,08:29:42.203000,2021-03-17,1615969782,1010,PD,pivot_turn,1,90_degrees,1.952000,On medication - On DBS,No,No,00:02:06.667,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:29:42.203000
2436,08:41:14.132000,2021-03-17,1615970474,1010,PD,pivot_turn,2,90_degrees,1.524000,On medication - On DBS,No,No,00:13:38.596,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:41:14.132000
2437,08:42:16.059000,2021-03-17,1615970536,1010,PD,pivot_turn,2,90_degrees,2.190000,On medication - On DBS,No,No,00:14:40.523,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:42:16.059000
2438,08:42:20.368999,2021-03-17,1615970540,1010,PD,pivot_turn,1,135_degrees,1.238000,On medication - On DBS,No,No,00:14:44.833,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:42:20.368999
2439,08:42:24.249999,2021-03-17,1615970544,1010,PD,pivot_turn,2,135_degrees,1.953000,On medication - On DBS,No,No,00:14:48.714,1010-1011_17.03.21_annotations_set1_from 16159...,2021-03-17 08:42:24.249999
2440,08:43:12.572000,2021-03-17,1615970592,1010,PD,pivot_turn,1,90_degrees,1.238000,On medication - On DBS,No,No,00:00:33.238,1010-1011_17.03.21_annotations_set6_from 16159...,2021-03-17 08:43:12.572000
2441,08:43:20.429000,2021-03-17,1615970600,1010,PD,pivot_turn,2,90_degrees,1.665999,On medication - On DBS,No,No,00:00:41.095,1010-1011_17.03.21_annotations_set6_from 16159...,2021-03-17 08:43:20.429000
2442,08:43:24.762000,2021-03-17,1615970604,1010,PD,pivot_turn,1,90_degrees,1.572000,On medication - On DBS,No,No,00:00:45.428,1010-1011_17.03.21_annotations_set6_from 16159...,2021-03-17 08:43:24.762000